// client-vue-ts-old/src/components/NavBar/NavBar.vue
<template>
    <div id="NavBar">
        <router-link to="/">Shabam</router-link> |
        <router-link to="/search">Search</router-link> |
        <router-link to="/catalog">Catalog</router-link>
    </div>
</template>

<script lang="ts" src="./NavBar.ts" />
<style lang="scss" src="./NavBar.scss" />

// client/src/components/NavBar/NavBar.tsx
import React, { FunctionComponent } from "react";
import "./NavBar.scss";
import {
    Link
} from "react-router-dom";

type Props = {

}

const NavBar: FunctionComponent<Props> = (props) => {
    return (
        <div id="NavBar">
            <Link to="/">Shabam</Link> |&nbsp;
            <Link to="/search">Search</Link> |&nbsp;
            <Link to="/catalog">Catalog</Link>
        </div>
    );
};

export default NavBar;
